#
# build and test ext-jsonreader on Travis CI - https://travis-ci.org/
#

language: php
sudo: false
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 5.7

env:
  - NO_INTERACTION=1 REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=php

script:
  - phpize
  - ./configure --enable-shared
  - make test
